<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\user\Entity\User;


/**
 * Implements hook_form_alter().
 */
function africassoc_forms_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_event_form') {
    $form['field_event_member']['widget'][0]['target_id']['#default_value'] = User::load(Drupal::currentUser()
      ->id());
  }

  if ($form_id == 'node_association_form') {
    $form['field_association_member']['widget'][0]['target_id']['#default_value'] = User::load(Drupal::currentUser()
      ->id());
  }
}
