<?php

/**
 * Implements hook_theme().
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 *
 * @return array
 */
function africassoc_pages_theme($existing, $type, $theme, $path): array {
  return [
    'fora_brussels_page' => [
      'variables' => [
        'fora_brussels' => [],
        'vgc' => [],
        'n22' => [],
        'subsidies' => [],
        'membership' => [],
        'activitySpace' => []
      ]
    ]
  ];
}
